import boto3
import json
import time
import urllib.parse

# AWS clients
s3 = boto3.client('s3')
transcribe = boto3.client('transcribe')
bedrock = boto3.client('bedrock-runtime', region_name='us-east-1')

# Your output bucket name
OUTPUT_BUCKET = 'voice-blog-output-lokesh'

def lambda_handler(event, context):
    print("Pipeline started")

    # Step 1 — Get the uploaded audio file details from the S3 event
    bucket = event['Records'][0]['s3']['bucket']['name']
    key = urllib.parse.unquote_plus(
        event['Records'][0]['s3']['object']['key']
    )
    print(f"Audio file received: s3://{bucket}/{key}")

    # Step 2 — Start transcription job
    job_name = f"voice-blog-{int(time.time())}"
    audio_uri = f"s3://{bucket}/{key}"

    transcribe.start_transcription_job(
        TranscriptionJobName=job_name,
        Media={'MediaFileUri': audio_uri},
        MediaFormat='mp3',
        LanguageCode='en-US',
        OutputBucketName=OUTPUT_BUCKET,
        OutputKey=f"transcripts/{job_name}.json"
    )
    print(f"Transcription job started: {job_name}")

    # Step 3 — Wait for transcription to complete
    while True:
        response = transcribe.get_transcription_job(
            TranscriptionJobName=job_name
        )
        status = response['TranscriptionJob']['TranscriptionJobStatus']
        print(f"Transcription status: {status}")

        if status == 'COMPLETED':
            break
        elif status == 'FAILED':
            raise Exception(f"Transcription job failed: {job_name}")

        time.sleep(10)

    # Step 4 — Fetch the transcript text from S3
    transcript_obj = s3.get_object(
        Bucket=OUTPUT_BUCKET,
        Key=f"transcripts/{job_name}.json"
    )
    transcript_data = json.loads(transcript_obj['Body'].read())
    transcript_text = transcript_data['results']['transcripts'][0]['transcript']
    print(f"Transcript retrieved: {transcript_text[:100]}...")

    # Step 5 — Send transcript to Bedrock (Claude) to write a blog post
    prompt = f"""You are a professional blog writer. 
Below is a spoken transcript. Rewrite it as a well-structured, 
engaging blog post with:
- A compelling title
- A short introduction
- Clear body paragraphs
- A conclusion

Fix any filler words, repetitions or grammar issues.
Return the blog post as a clean HTML page with basic styling.

Transcript:
{transcript_text}"""

    bedrock_response = bedrock.invoke_model(
        modelId='anthropic.claude-3-haiku-20240307-v1:0',
        body=json.dumps({
            "anthropic_version": "bedrock-2023-05-31",
            "max_tokens": 2000,
            "messages": [
                {"role": "user", "content": prompt}
            ]
        })
    )

    blog_html = json.loads(
        bedrock_response['body'].read()
    )['content'][0]['text']
    print("Blog post generated by Bedrock")

    # Step 6 — Save the blog post HTML to S3 output bucket
    post_key = f"posts/{job_name}.html"
    s3.put_object(
        Bucket=OUTPUT_BUCKET,
        Key=post_key,
        Body=blog_html,
        ContentType='text/html'
    )
    print(f"Blog post saved to s3://{OUTPUT_BUCKET}/{post_key}")

    # Step 7 — Return the public URL
    blog_url = f"http://{OUTPUT_BUCKET}.s3-website-us-east-1.amazonaws.com/{post_key}"
    print(f"Blog live at: {blog_url}")

    return {
        "statusCode": 200,
        "body": json.dumps({
            "message": "Blog post created successfully",
            "url": blog_url
        })
    }